### ISSUE TITLE
Mandelbrot BF Infinite Loop

### ISSUE THREAD

**Issue by linux4life798** [vishen/go-brainfunk#1]
This project is really interesting!

Unfortunately, it seems to have some issues with https://github.com/erikdubbelboer/brainfuck-jit/blob/master/mandelbrot.bf .

**Comment by vishen** [comment]
Thanks! This project is still under development and I know it is missing some key features of brainfuck, but I didn't think it would cause infinite-loops anywhere. I'll take a look at it!

**Comment by linux4life798** [comment]
Yeah, no worries!

I didn't exactly verify it was looping, but I had to kill it after a few
mins.

**Comment by vishen** [comment]
You were correct, I was able to verify it last night. I didn't implement the looping correctly, I didn't know how to forward-jump when outputting machine code and the case when you need to jump forward from `[` to the corresponding `]` didn't come up in any of the test programs I was looking at so I thought that maybe it wasn't needed. 

But I think I have an approach now, so hopefully I will have that implemented soon!

**Comment by vishen** [comment]
This should be working now!

**Comment by linux4life798** [comment]
Ohh awesome! I'll check it out over the weekend.
